config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'

  # Devise custom routing
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
  end

  # Dashboard
  get 'dashboard', to: "dashboard#index"

  # Projects
  resources :projects

  # Tasks
  resources :projects do
    resources :tasks
  end

  # Endpoints for sorting functionality via task_sort js
  resources :tasks do
    collection do
      patch :sort
    end
  end
  # get 'projects/:id/tasks', to: 'tasks#index', as: "tasks_path"
  # get 'projects/:id/tasks/new', to: 'tasks#new', as: "new_task_path"
  # post 'projects/:id/tasks/new', to: 'tasks#create'
  # get 'projects/:id/tasks/:task_id', to: 'tasks#show', as: "task_path"
  # post 'projects/:id/tasks/:task_id', to: 'tasks#update'
  # get 'projects/:id/tasks/:task_id/edit', to: 'tasks#edit', as: "edit_task_path"
  # delete 'projects/:id/tasks/:task_id', to: 'tasks#destroy'

  get "calendar", to: "calendar#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :tasks, :dependent => :delete_all 
    accepts_nested_attributes_for :tasks, :reject_if => proc { |attributes| attributes['name'].blank? }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = current_user.projects.all
    end
    def show
        get_project
        get_tasks(@project)
    end
    def new
        create_new_project
    end
    def create
        create_new_project(project_params)
        if @project.save
            redirect_to dashboard_path
        else
            render 'new'
        end
    end
    def edit
        get_project
    end
    def update
        get_project
        if @project.update(project_params)
            redirect_to project_path(@project)
        else
            render 'edit'
        end
    end
    def destroy
        get_project
        @project.destroy
        redirect_to projects_path
    end

private
    def project_params
        params.require(:project).permit(:title)
    end
    def get_project
        @project = current_user.projects.find_by(id:params[:id])
    end
    def get_tasks(project)
        if project
            @task = project.tasks.build
            # sorting
            @items = project.tasks.order(:position).all
        end
    end
    def create_new_project(args = nil)
        @project = current_user.projects.build(args)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def edit_task_item(task_item)
        @project = Project.find_by(id: params[:id])
        @task = @project.tasks.find_by(id:task_item.id)
    end
end

app/views/projects/_show_tasks.erb
<% if items%>

    <div id="tasks" class="list-group" data-url="<%= sort_tasks_path%>">
        <% items.each do |task| %>
            <% unless task.name.nil?%>
                
                <div class="card card-body list-group-item" id=<%=dom_id(task)%> >
                    <%= form_for [project, edit_task_item(task)] do |f|%>
                        <div class="edit_task_field">
                            <%= f.text_field :name, :class => "hidden-form-field" %>
                            <%# ADD DATE FIELD HERE https://jqueryui.com/datepicker/ %>
                            <%= f.date_select :date, order: [:day, :month, :year] %>
                            <%# select_datetime Date.today, :prefix => :date, :class => "form-control"%>
                            <%= link_to "X", project_task_path(project, task), method: :delete, :class=>"btn btn-danger btn-sm float-right"%>
                        </div>
                    <% end %>
                </div>

            <% end %>
        <% end %>
    </div>

<% else %>
    No tasks.
<% end %>

app/views/projects/_task_form.erb
<div id="create-task-form-project-view" class="mb-0 pb-0">
    <%= form_for [project, task] do |f|%>
        <div class="input-group mb-0">
            <%= f.text_field :name, :class => "form-control" %>
            <div class="input-group-append">
                <%= f.submit "+", :class => "btn btn-outline-success"%>
            </div>
        </div>
        
    <% end %>
</div>

app/views/projects/edit.html.erb
<div id="edit-project-form-heading" class="container text-center">
  <h2>Edit Project</h2>
</div>

<div id="edit-project-form" class="container w-50">
    <%= form_with(model: @project) do |f|%>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, :class => "form-control"%>
        </div>

        <div>
            <%= f.submit "Save Changes", :class => "btn btn-success" %> <%= link_to "Delete Project", project_path(@project), method: :delete, :class => "btn btn-danger"%>
        </div>
    <% end %>
</div>

app/views/projects/index.html.erb
<div class="container">
    <h2> Projects </h2>

    <br />
    <div>
        <%= link_to "Create New Project", new_project_path, :class => "btn btn-primary" %>
    </div>
    <br />

    <% if @projects.any? %>
        <% @projects.each do |project|%>

            <div class="card card-body">
                <h4><%= project.title %></h4>
                <%= link_to "View", project_path(project) %>
                <%= link_to "Edit", edit_project_path(project) %>
                <%= link_to "Delete", project_path(project), method: :delete %>
            </div>

        <% end %>

    <% else %>
    <br />
        <p>No projects to display.</p>
    <% end %>
</div>

app/views/projects/new.html.erb
<div id="create-project-form-heading" class="container text-center">
  <h2>New Project</h2>
</div>

<div id="create-project-form" class="container w-50">
    <%= form_with(model: @project) do |f|%>
        <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, :class => "form-control"%>
        </div>
        <div>
            <%= f.submit "Create", :class => "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/projects/show.html.erb
<% unless @project.nil?%>
    <div class="container w-50">
        <h4 class="text-center"> <%= @project.title %> </h4>
        <p class="text-secondary"> *dev note: must hit enter to save edits. Need to add feature of dynamic "save" button </p>
        <br />
        <h3> Tasks </h3>
        <%= render partial: 'task_form', :locals => {:project => @project, :task => @task} %>
        <%= render partial: 'show_tasks', :locals =>{:project => @project, :items => @items} %>
        <br />
        <div class="container text-center mt-3">
            <%= link_to "Edit Project", edit_project_path(@project), :class => "btn btn-primary" %>
        </div>
    </div>

<% end %>