config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'

  # Devise custom routing
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
  end

  # Dashboard
  get 'dashboard', to: "dashboard#index"

  # Projects
  resources :projects

  # Tasks
  resources :projects do
    resources :tasks
  end

  # Endpoints for sorting functionality via task_sort js
  resources :tasks do
    collection do
      patch :sort
    end
  end
  # get 'projects/:id/tasks', to: 'tasks#index', as: "tasks_path"
  # get 'projects/:id/tasks/new', to: 'tasks#new', as: "new_task_path"
  # post 'projects/:id/tasks/new', to: 'tasks#create'
  # get 'projects/:id/tasks/:task_id', to: 'tasks#show', as: "task_path"
  # post 'projects/:id/tasks/:task_id', to: 'tasks#update'
  # get 'projects/:id/tasks/:task_id/edit', to: 'tasks#edit', as: "edit_task_path"
  # delete 'projects/:id/tasks/:task_id', to: 'tasks#destroy'

  get "calendar", to: "calendar#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :user
    has_many :tasks, :dependent => :delete_all 
    accepts_nested_attributes_for :tasks, :reject_if => proc { |attributes| attributes['name'].blank? }
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
    before_save :default_values
    def default_values
        self.date ||= DateTime.now
    end
    def start_time
        self.date ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :tasks, :through => :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
    def index
        @tasks = current_user.tasks.all
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!
    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        @projects = current_user.projects.all
    end
    def show
        get_project
        get_tasks(@project)
    end
    def new
        create_new_project
    end
    def create
        create_new_project(project_params)
        if @project.save
            redirect_to dashboard_path
        else
            render 'new'
        end
    end
    def edit
        get_project
    end
    def update
        get_project
        if @project.update(project_params)
            redirect_to project_path(@project)
        else
            render 'edit'
        end
    end
    def destroy
        get_project
        @project.destroy
        redirect_to projects_path
    end

private
    def project_params
        params.require(:project).permit(:title)
    end
    def get_project
        @project = current_user.projects.find_by(id:params[:id])
    end
    def get_tasks(project)
        if project
            @task = project.tasks.build
            # sorting
            @items = project.tasks.order(:position).all
        end
    end
    def create_new_project(args = nil)
        @project = current_user.projects.build(args)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
    end
    def new
        get_project_from_params
        build_task
    end
    def create
        get_project_from_params
        build_task(task_params)

        if @task.save
            redirect_to @project
        else
            render 'new'
        end
    end
    def edit
        get_task_from_params
        get_project_from_task
    end
    def update
        get_task_from_params
        get_project_from_task
        if @task.update(task_params)
            redirect_to @project
        end
    end
    def destroy
        get_project_from_params
        get_task_from_params
        @task.destroy
        redirect_to @project
    end
    def sort
        params[:task].each_with_index do |id,index|
            Task.where(id: id).update_all(position: index + 1)
        end

        head :ok
    end
    
private
    def task_params
        params.require(:task).permit(:name, :date)
    end
    def get_project_from_params
        @project = Project.find_by(id: params[:project_id])
    end
    def get_project_from_task
        @project = Project.find_by(id: @task.project_id)
    end
    def build_task(args=nil)
        @task = @project.tasks.build(args)
    end
    def get_task_from_params
        @task = Task.find_by(id:params[:id])
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def edit_task_item(task_item)
        @project = Project.find_by(id: params[:id])
        @task = @project.tasks.find_by(id:task_item.id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <%= link_to 'BaseHub', root_path, :class => 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>

        <%= link_to "Dashboard", dashboard_path, :class=> 'nav-item nav-link'%>
        <%= link_to "Projects", projects_path, :class=> 'nav-item nav-link' %>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-item nav-link' %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-item nav-link'  %>
      
      <% else %>
        <%= link_to 'Home', root_path, :class => 'nav-item nav-link' %>
        <%= link_to "Sign up", register_path, :class => 'nav-item nav-link'  %>
        <%= link_to "Login", login_path, :class => 'nav-item nav-link'  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= render 'layouts/header' %>
    <br/>
    <br/>
    <%= yield %>
  </body>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>